src/Entity/Voiture.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\VoitureRepository")
 */
class Voiture
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Numero;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Service", inversedBy="voitures")
     */
    private $service;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Utilisateurs", inversedBy="voitures")
     */
    private $responsable;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Reservation", mappedBy="voiture")
     */
    private $reservations;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Pointage", mappedBy="voiture")
     */
    private $pointages;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Libelle;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $emplacement;

    /**
     * @ORM\Column(type="integer")
     */
    private $kilometrage;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Entretien", mappedBy="voiture")
     */
    private $entretiens;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Suivi", mappedBy="voiture")
     */
    private $suivis;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Controle", mappedBy="voiture")
     */
    private $controles;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Assurance", mappedBy="voiture")
     */
    private $assurances;

    /**
     * @ORM\Column(type="boolean")
     */
    private $etat;

    public function __construct()
    {
        $this->reservations = new ArrayCollection();
        $this->pointages = new ArrayCollection();
        $this->entretiens = new ArrayCollection();
        $this->suivis = new ArrayCollection();
        $this->controles = new ArrayCollection();
        $this->assurances = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumero(): ?string
    {
        return $this->Numero;
    }

    public function setNumero(string $Numero): self
    {
        $this->Numero = $Numero;

        return $this;
    }

    public function getService(): ?Service
    {
        return $this->service;
    }

    public function setService(?Service $service): self
    {
        $this->service = $service;

        return $this;
    }

    public function __toString()
    {
        return ''.$this->getNumero().' - '.$this->getLibelle();
    }

    public function getResponsable(): ?Utilisateurs
    {
        return $this->responsable;
    }

    public function setResponsable(?Utilisateurs $responsable): self
    {
        $this->responsable = $responsable;

        return $this;
    }

    /**
     * @return Collection|Reservation[]
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservation $reservation): self
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations[] = $reservation;
            $reservation->setVoiture($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): self
    {
        if ($this->reservations->contains($reservation)) {
            $this->reservations->removeElement($reservation);
            // set the owning side to null (unless already changed)
            if ($reservation->getVoiture() === $this) {
                $reservation->setVoiture(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Pointage[]
     */
    public function getPointages(): Collection
    {
        return $this->pointages;
    }

    public function addPointage(Pointage $pointage): self
    {
        if (!$this->pointages->contains($pointage)) {
            $this->pointages[] = $pointage;
            $pointage->setVoiture($this);
        }

        return $this;
    }

    public function removePointage(Pointage $pointage): self
    {
        if ($this->pointages->contains($pointage)) {
            $this->pointages->removeElement($pointage);
            // set the owning side to null (unless already changed)
            if ($pointage->getVoiture() === $this) {
                $pointage->setVoiture(null);
            }
        }

        return $this;
    }

    public function getLibelle(): ?string
    {
        return $this->Libelle;
    }

    public function setLibelle(string $Libelle): self
    {
        $this->Libelle = $Libelle;

        return $this;
    }

    public function getEmplacement(): ?string
    {
        return $this->emplacement;
    }

    public function setEmplacement(string $emplacement): self
    {
        $this->emplacement = $emplacement;

        return $this;
    }

    public function getKilometrage(): ?int
    {
        return $this->kilometrage;
    }

    public function setKilometrage(int $kilometrage): self
    {
        $this->kilometrage = $kilometrage;

        return $this;
    }

    /**
     * @return Collection|Entretien[]
     */
    public function getEntretiens(): Collection
    {
        return $this->entretiens;
    }

    public function addEntretien(Entretien $entretien): self
    {
        if (!$this->entretiens->contains($entretien)) {
            $this->entretiens[] = $entretien;
            $entretien->setVoiture($this);
        }

        return $this;
    }

    public function removeEntretien(Entretien $entretien): self
    {
        if ($this->entretiens->contains($entretien)) {
            $this->entretiens->removeElement($entretien);
            // set the owning side to null (unless already changed)
            if ($entretien->getVoiture() === $this) {
                $entretien->setVoiture(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Suivi[]
     */
    public function getSuivis(): Collection
    {
        return $this->suivis;
    }

    public function addSuivi(Suivi $suivi): self
    {
        if (!$this->suivis->contains($suivi)) {
            $this->suivis[] = $suivi;
            $suivi->setVoiture($this);
        }

        return $this;
    }

    public function removeSuivi(Suivi $suivi): self
    {
        if ($this->suivis->contains($suivi)) {
            $this->suivis->removeElement($suivi);
            // set the owning side to null (unless already changed)
            if ($suivi->getVoiture() === $this) {
                $suivi->setVoiture(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Controle[]
     */
    public function getControles(): Collection
    {
        return $this->controles;
    }

    public function addControle(Controle $controle): self
    {
        if (!$this->controles->contains($controle)) {
            $this->controles[] = $controle;
            $controle->setVoiture($this);
        }

        return $this;
    }

    public function removeControle(Controle $controle): self
    {
        if ($this->controles->contains($controle)) {
            $this->controles->removeElement($controle);
            // set the owning side to null (unless already changed)
            if ($controle->getVoiture() === $this) {
                $controle->setVoiture(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Assurance[]
     */
    public function getAssurances(): Collection
    {
        return $this->assurances;
    }

    public function addAssurance(Assurance $assurance): self
    {
        if (!$this->assurances->contains($assurance)) {
            $this->assurances[] = $assurance;
            $assurance->setVoiture($this);
        }

        return $this;
    }

    public function removeAssurance(Assurance $assurance): self
    {
        if ($this->assurances->contains($assurance)) {
            $this->assurances->removeElement($assurance);
            // set the owning side to null (unless already changed)
            if ($assurance->getVoiture() === $this) {
                $assurance->setVoiture(null);
            }
        }

        return $this;
    }

    public function getEtat(): ?bool
    {
        return $this->etat;
    }

    public function setEtat(bool $etat): self
    {
        $this->etat = $etat;

        return $this;
    }
}

src/Form/ReservationType.php
<?php

namespace App\Form;

use App\Entity\Reservation;
use App\Entity\Utilisateurs;
use App\Service\ReservationService;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;

class ReservationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('personne')
            ->add('debut', DateTimeType::class,array(
                'date_widget' => 'single_text',
                'time_widget' => 'choice',
                'minutes' => array('0','15','30','45')

            ))
            ->add('fin', DateTimeType::class, array(
                'label' => false,
                'date_widget' => 'single_text',
                'time_widget' => 'choice',
                'minutes' => array('0','15','30','45')
            ))
            ->add('optPlace', ChoiceType::class, array(
                'choices'  => array(
                    'Indifférent' => 0,
                    '2 places' => 2,
                    '4 places' => 4)
            ))
            ->add('load', SubmitType::class, array('label' => 'Charger', 'attr' => ['class' => 'btn btn-primary']))
            ->add('save', SubmitType::class, array('label' => 'Sauvegarder','attr' => ['class' => 'btn btn-success', 'onclick' => 'sauvegardeEnCours()']));
            
            
            /*$builder->addEventListener(
                FormEvents::PRE_SUBMIT,
                function(FormEvent $event)
                {
                    $form = $event->getForm();
                    $data = $event->getData();
                    $form->add('save', SubmitType::class, array('label' => 'Sauvegarder','attr' => ['class' => 'btn btn-success', 'onclick' => 'sauvegardeEnCours()']));
                }
            );*/
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Reservation::class,
            'csrf_protection' => true,
            'csrf_field_name' => '_token',
            // important part; unique key
            'csrf_token_id'   => 'form_intention',
        ]);
        
    }
}

src/Controller/ReservationController.php
<?php

namespace App\Controller;

use App\Entity\Voiture;
use App\Entity\Reservation;
use App\Form\ReservationType;
use App\Service\ReservationService;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class ReservationController extends AbstractController
{
    /**
     * @Route("/reservation", name="reservation")
     */
    public function index(Request $req, ReservationService $RS, ObjectManager $manager, \Swift_Mailer $mailer)
    {
        $reservation = new Reservation();
        $reservation->setPersonne($this->getUser());
        $form = $this->createForm(ReservationType::class, $reservation);
        $form->handleRequest($req);

        if($form->isSubmitted() && $form->isValid())
        {
            $this->get("security.csrf.token_manager")->refreshToken("form_intention");
            $em = $this->getDoctrine()->getRepository(Voiture::class);
            if($form->get('load')->isClicked())
            {   
                //Vérification des horaires renseignés
                if($reservation->getDebut() >= $reservation->getFin())
                {
                    return $this->render('reservation/reservation.html.twig', [
                        'form' => $form->createView(),
                        'charger' => false,
                    ]);
                }

                //charger les voitures du service disponible
                $voitures = $RS->GetVoituresDispoService($this->getUser(), $reservation->getDebut(), $reservation->getFin(),$reservation->getOptplace());
                $service = 'interne';
                if($voitures == null)
                {
                    $service ='externe';
                    $voituresTemp = $em->findOutsideService($this->getUser()->getService()->getId());
                    $voitures = $RS->GetVoituresDispo($voituresTemp, $reservation->getDebut(), $reservation->getFin(), $reservation->getOptPlace());
                }

                return $this->render('reservation/reservation.html.twig', [
                    'form' => $form->createView(),
                    'charger' => true,
                    'localité' => $service,
                    'voitures' => $voitures
                ]);
            }
            elseif($form->get('save')->isClicked())
            {
                $this->addFlash('Ok','Action validée');
                $data = $form->getData();
                $reservation->setVoiture($em->find($_POST['voitureChoisie']));
                $reservation->setPersonne($this->getUser());
                $reservation->setEtat(false);
                $manager->persist($reservation);
                $manager->flush();

                $this->EnvoyerMail($mailer, $reservation);
                return $this->render('reservation/recapitulatif.html.twig', [
                    'reservation' => $reservation
                ]);
            }
        }

        return $this->render('reservation/reservation.html.twig', [
            'form' => $form->createView(),
            'charger' => false,
        ]);
    }

    public function EnvoyerMail(\Swift_Mailer $mailer, $reservation)
    {
        $message = (new \Swift_Message('Reservation de véhicule'))
        ->setFrom('flotte.auto@sip-picardie.com')
        ->setTo(
            [
                $reservation->getPersonne()->getEmail(),
                $reservation->getVoiture()->getResponsable()->getEmail()
            ])
        ->setBcc('leconte.kevin@sip-picardie.com')
        ->setBody(
            $this->renderView(
                'emails/reservation.html.twig', 
                [
                    'reservation' => $reservation
                ]
            ),
            'text/html'
        );
        $mailer->send($message);
    }

}

templates/reservation/recapitulatif.html.twig
{% extends 'base.html.twig' %}

{% block title %}Récapitulatif{% endblock %}

{% block body %}
<div class="jumbotron">
    <h1 class="display-3">Reservation enregistrée</h1>
    <hr class="my-4">
    <p class="lead">Récapitulatif de votre réservation</p>
    <div class="row">
        <div class="col-6">
            <p>Reservation n°{{ reservation.id }}</p>
            <p>Début : {{ reservation.debut|date("d/m/Y H:i", "Europe/Paris") }}</p>
            <p>Fin : {{ reservation.fin|date("d/m/Y H:i", "Europe/Paris") }}</p>
        </div>
        <div class="col-6">
            <p>Voiture n° {{ reservation.voiture.numero }}</p>
            <p>Modèle : {{ reservation.voiture.libelle }}</p>
            <p>Emplacement : {{ reservation.voiture.emplacement }}</p>
            <p>Responsable : {{ reservation.voiture.Responsable }}</p>
        </div>
    </div>
    <hr class="my-4">
    <p class="lead">
        <a class="btn btn-primary btn-lg" href="{{ path('tableauDeBord') }}" role="button">Retour au tableau de bord</a>
    </p>
</div>
{% endblock %}

templates/reservation/reservation.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reservation{% endblock %}

{% block body %}

<div class="container">
    <br />
    <div class="row">
        <div class="col-lg-12">
            <h1 class="text-center">Réservation</h1>
        </div>
    </div>
{{ form_start(form) }}
    <br />
    <div class="row">
        <h4>Selectionnez vos horaires :</h4>
    </div>
    <br />
    <div class="row">
        <div class="col-lg-6">
            <div class="card text-white bg-primary">
                <div class="card-header">Début</div>
                <div class="card-body">
                    <h4 class="card-title">Horaires</h4>
                    <div class="offset-2">
                        <label>Date :</label>
                        {{form_widget(form.debut.date)}}
                        <br/>
                        <div class="form-inline">
                            <label>Heure :</label>
                            {{form_widget(form.debut.time)}}
                        </div>
                    </div>
                </div>
            </div>      
        </div>
        <div class="col-lg-6">
            <div class="card text-white bg-secondary">
                <div class="card-header">Fin</div>
                <div class="card-body">
                    <h4 class="card-title">Horaires</h4>
                    <div class="offset-2">
                        <label>Date :</label>
                        {{form_widget(form.fin.date,  {'label': 'Date :'})}}
                        <br/>
                        <div class="form-inline">
                            <label>Heure :</label>
                            {{form_widget(form.fin.time)}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-lg-12">
            <div class="card text-white bg-info mb-3">
                <div class="card-header">Options</div>
                <div class="card-body">
                    <div class="offset-2">
                        <label>Nombre de places souhaitées :</label>
                        {{form_widget(form.optPlace)}}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br />

    <!--  Chargement     -->
    {% if charger == true %}
        <div class="row">
            {{form_row(form.load)}}
        </div>

        <br/>
        <hr></hr>
        <br/>
        {% if localité == "interne" %}
            <div class="row">
                <div class="col-lg-12">
                    <div class="card text-white bg-success">
                        <div class="card-header">Voitures</div>
                        <div class="card-body">
                            <h4 class="card-title">Voitures de service disponible</h4>
                            <div class="offset-2">
        {% else %}
            <div class="row">
                <div class="col-lg-12">
                    <div class="card text-white bg-warning">
                        <div class="card-header">Voitures</div>
                        <div class="card-body">
                            <h4 class="card-title">Aucune voiture du service disponible</h4>
                            <h4 class="card-title">Voiture des autres services disponible</h4>
                            <div class="offset-2">


        {% endif %}
                                <select id="voitureChoisie" name="voitureChoisie">
                                    {% for voiture in voitures %}
                                        <option value="{{ voiture.id }}">Voiture n°{{ voiture }} - {{voiture.service.nom}} - {{voiture.responsable}} </option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                </div>
            </div>
        </div>
        <br />
        {{form_row(form.save)}}
        <!--<button class="btn btn-primary" type="button" disabled>
            <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
            Loading...
        </button>-->
    {% else %}
        <div class="row">
            {{form_row(form.load)}}
        </div>
        <div class="row" style="display:none">
            {{form_row(form.save)}}
        </div>
    {% endif %}
    <!--                                                   -->

    <div class="row">
        {{form_row(form.personne.setRendered())}}
    </div>
</div>
{{ form_end(form) }}

{% endblock %}
{% block javascripts %}
<script type="text/javascript">
    /*function sauvegardeEnCours()
    {
        var button = document.getElementById('reservation_save');
        button.innerHTML = "<span class='spinner-border spinner-border-sm' role='status' aria-hidden='true'></span>Sauvegarde ...";
        button.disabled = true;
    }*/
</script>

{% endblock %}